name: CI on feature branch
on:
  push:
    branches:
      - "*"
      - "!master"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: .node-version
